version: "3.7"

services:
  db:
    image: postgres
    container_name: db_app
    command: -p 1225
    expose:
      - 1225
    env_file:
      - .env
    volumes:
      - ./db/:/var/lib/postgresql/data
  app:
    image: wafflelios/rest-service:latest
    env_file:
      - .env
    container_name: fastapi_app
    command: ['/fastapi_app/docker/app.sh']
    ports:
      - 9999:8000
    depends_on:
      - db

