"""User table creation

Revision ID: a4cea51835b7
Revises: 
Create Date: 2023-06-26 17:22:53.342933

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a4cea51835b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('surname', sa.String(), nullable=False),
                    sa.Column('login', sa.String(), nullable=False),
                    sa.Column('hashed_password', sa.String(), unique=True, nullable=False),
                    sa.Column('salary', sa.Integer(), nullable=False),
                    sa.Column('date_of_next_increase', sa.Date(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
